### PR TITLE
[MDCT-39] Favicon Update

### PR DESCRIPTION
**Pull request by karla-vm**
https://qmacbis.atlassian.net/browse/MDCT-39

Updating favicon from create-react-app to MDCT icon, tested and verified on local environment.

### CODE REVIEW

**Review by gmrabian — CHANGES_REQUESTED** [review]
Looks like it's trying to merge from your fork into a carts branch. Can you update it to merge to master?

**Comment by karla-vm** [comment]
> Looks like it's trying to merge from your fork into a carts branch. Can you update it to merge to master?

Just noticed that! It should be good now.

**Review by braxex — APPROVED** [review]

**Review by juliuscaesar — APPROVED** [review]
Favicon. Fave-icon?

**Comment by karla-vm** [comment]
> 

Favorite-Icon?

**Comment by juliuscaesar** [comment]
Fa-vi-con.

**Review by gmrabian — APPROVED** [review]

**Pull request merged**
