### PR TITLE
MDCT-162: Remove _overrides.scss

### PR DESCRIPTION
**Pull request by juliuscaesar**
# Description

[MDCT-162: Reorganize and clean up existing global override styling](https://qmacbis.atlassian.net/browse/MDCT-162)

## How to test

Regression test styling to ensure nothing looks weird, funky, or broken.

## Dependencies

None.

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist

- [x] I have performed a self-review of my code
- [x] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [x] Necessary analytics were added, or no new analytics were required
- [x] I have made corresponding changes to the documentation
- [x] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

### CODE REVIEW

**Review by karla-vm — APPROVED** [review]

**Review by gmrabian — APPROVED** [review]
overall looks good - I'm guessing the header, footer, all the other stuff that was removed from overrides already existed in those other files?

**Comment by gmrabian** [comment]
also wondering if any of this will conflict with @karla-vm PR on the dead zones

**Comment by juliuscaesar** [comment]
> also wondering if any of this will conflict with @karla-vm PR on the dead zones

Yes! A lot of the styles were duplicated.

**Comment by juliuscaesar** [comment]
> overall looks good - I'm guessing the header, footer, all the other stuff that was removed from overrides already existed in those other files?

Yes! A lot of the styles were duplicates.

**Pull request merged**
