### PR TITLE
Revert "Add better checkbox support, dynamic labels for ranges (FPL)"

### PR DESCRIPTION
**Pull request by cannandev**
Reverts 18F/cms-carts-seds#317

When Section 1 part 1 question 2a is selected, throws undefined error.  This is undefined:
```
 label={this.props.fieldLabels[0][0]}
```

### CODE REVIEW

**Review by jgillis1 — APPROVED** [review]

**Comment by jgillis1** [comment]
@cannandev There are conflicts against master. Could you please resolve?

**Comment by andrewadcock** [comment]
I don't believe we need this PR any more. It was handled in another commit

**Comment by jgillis1** [comment]
@cannandev If Andrew's comment is correct, could you close this PR?

**Comment by andrewadcock** [comment]
This was taken care of in another commit

**Pull request closed without merging**
