### PR TITLE
MDCT-354: Main Page Alignment issue

### PR DESCRIPTION
**Pull request by ntsummers1**
# Description

Fixes [MDCT-354](https://qmacbis.atlassian.net/browse/MDCT-354)

Fixes alignment on the main page and the Reports page. Does not fix the alignment on Get Help or the users account page intentionally. Those pages have different main content widths that were intended to be like that. Might be something we want to address going forward.

Alignment fix

## How to test

./dev local
Log in as a state user or the admin
Checkout the page in all its aligned glory (Except for the soon to be deleted CMS user note)

## Dependencies

# Get it done

Now that the PR is open this is what happens next

## Code authors checklist

- [x] I have performed a self-review of my code
- [x] I have added thorough tests. [Testing Doc](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research)
- [x] Necessary analytics were added, or no new analytics were required
- [x] I have made corresponding changes to the documentation
- [x] I have assigned the PR to myself

## Reviewers Checklist (Two different people)

- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

## Assignee

- [ ] I have closed the PR after the review and necessary changes (squashing preferred)

### CODE REVIEW

**Review by BearHanded — DISMISSED** [review]

**Review by BearHanded — APPROVED** [review]

**Comment by gmrabian** [comment]
From what I can tell the header and the footer are aligned, and the inner content has an indent. Just checking this is expected.

This branch:
Screen Shot 2022-06-23 at 12 37 49 PM

Main:
Screen Shot 2022-06-23 at 12 38 22 PM

**Comment by ntsummers1** [comment]
That indents intended. I looked at how the pages were setup and the padding on the inner content was put there on purpose. Going forward with design it looks like they'll want to move things around a little (See the get help page) so the width of the content isn't the same as the header and footer.

**Comment by ntsummers1** [comment]
Should mention too that the original screenshot in this was my first pass fix which i liked until i realized how much page structure it changed and the original intention and feedback from get-help page designers, hence my prior comment.

**Review by gmrabian — APPROVED** [review]
thanks for the response

**Pull request merged**
