### PR TITLE
prevent state name from extending past the sidebar column

### PR DESCRIPTION
**Pull request by britt-mo**
### Description
The state name was extending past the sidebar column and at times overlapping with the report text:

Screenshot 2024-07-26 at 10 16 39 AM

This change will make the state name drop below the state icon if the name exceeds the column width.

### Related ticket(s)

CMDCT-3876

---
### How to test
Login, enter a report, play around with the state name. use devtools to change the state name to different lengths and resize the page to see the ways the text moves.

### Notes

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by gmrabian — CHANGES_REQUESTED** [review]
Blocking due to style change not expected in ticket

The admin view has a gap now (also did admin always not have the state name and logo?)

https://github.com/user-attachments/assets/b7ae604b-9632-4b1f-b3c7-597a5f692dc6

**Review by ntsummers1 — COMMENTED** [review]
Looking much better! My only question is what should we do with states with longer continuous names, specifically something like Massachusetts. Right now it'll do the same thing:

Screenshot 2024-08-22 at 9 54 37 AM

We could trim it to the max width of the sidebar, so something like this: 

Screenshot 2024-08-22 at 9 51 42 AM

or even add an elipsis:

Screenshot 2024-08-22 at 10 21 15 AM

I'm not in love with either of these options though, so I'm curious on your thoughts!

**Comment by britt-mo** [comment]
@ntsummers1 I would love to shrink the state name text size itself to just fit the container...not sure if that's an option!

**Review by gmrabian — APPROVED** [review]
Text wrap looks good! admin spacing is correct too

Screenshot 2024-08-22 at 4 06 01 PM

**Review by ntsummers1 — APPROVED** [review]

**Pull request merged**
