### PR TITLE
Add hint text to QuestionComponent

### PR DESCRIPTION
**Pull request by jgillis1**
Add `hint: {question.hint} `to each component so hint text from the JSON is shown in the UI.

Addresses #539 

See Section 3h Part 2 Question 1 for example.

### CODE REVIEW

**Review by andrewadcock — COMMENTED** [review]
Looks good to me!

**Review by mblevins-collabralink — APPROVED** [review]

**Comment by mblevins-collabralink** [comment]
Text is appearing in section as described.

**Review by cl-adavyd — APPROVED** [review]

**Comment by jgillis1** [comment]
QA Review has been completed and the PR is ready for 18F review.

**Review by mgwalker — APPROVED** [review]
👍

**Pull request merged**
