### PR TITLE
Populating ACS data for uninsured children in API - moving FMAP

### PR DESCRIPTION
**Pull request by kaitlin**
Resolves the bottom 5 checkboxes in the list in #477 . This PR does a few things:

- Creates a stubbed out state model in the database and API (just name and code/abbrev for now but could store other things here)
- Creates an ACS data model, loads ACS data on uninsured children under 200% FPL for 2014-2019 from fixtures (original, cleaned CSVs also included)
- Removes the previous FMAP endpoint, and instead loads that data (and the ACS) data as part of the new state endpoint (e.g. `http://localhost:8000/state/AK/`)
- Removes what seems like an extra `generate_fixtures.py` file in the management command directory (@tadhg-ohiggins let me know if this is being used somewhere and I can restore)
- Tidies up some URL routing, groups the data loading in `docs/generate_fixtures.py` into functions
- Adds a minimal test file for the state API endpoint

Screen Shot 2020-09-20 at 10 55 25 PM

### CODE REVIEW

**Review by cl-adavyd — COMMENTED** [review]
Good afternoon,

is there a reason why numerical data is represented via different data types?
For example, number_uninsured is an integer, while percent_uninsured is a string.

**Comment by kaitlin** [comment]
@tonydavydets because integers are represented the same everywhere, but I didn't want a fixed-precision decimal value to be converted to a floating point number inadvertently. AFAIK it's not actually used in a calculation -- just a reference table for the user.

**Comment by tonydavydets** [comment]
> @tonydavydets because integers are represented the same everywhere, but I didn't want a fixed-precision decimal value to be converted to a floating point number inadvertently. AFAIK it's not actually used in a calculation -- just a reference table for the user.

**Comment by tonydavydets** [comment]
I see.  Could we please change all numerical data to be represented as numbers / floats?

Having a true representation of data (meaning, integers are represented as integers, floats as floats, etc.) gives us more uniformity, takes guessing out of the question (is a number truly a number or a string), and lastly, gives us the ability to reformat display with one line of configurable code as opposed to changing the entirety of our data / doing extensive regression testing, etc.

**Comment by kaitlin** [comment]
Hmm I see what you're saying, and it does seem like it would make it more consistent with how this data is represented in the dummy state section data. In this case, I'm relying on the default serialization behavior of Django Rest Framework, which has attempted to set a sane default based on the majority of use cases (and presumably because of the float vs Decimal precision issue). For the numbers we're dealing with I think it's fine, but the only way to change this without digging into the internals of DRF is to [use a setting in `settings.py`](https://www.django-rest-framework.org/api-guide/settings/#coerce_decimal_to_string) that would enforce this behavior at a project level. That probably won't be an issue since I think so far I'm the only person who has serialized from any Python objects that aren't primitive types. I'll push a commit now.  Thanks!

**Review by cl-adavyd — APPROVED** [review]

**Pull request merged**
