### PR TITLE
Update Section 1 per DSCP feedback

### LINKED ISSUE #415: update Section 1 per DSCP feedback
Any "Yes" responses should prompt users to enter details for why changes have been made

When section 1 renders, the additional children must also render.

AC:

- [x] Consult with Erin

- [ ] Change JSON

- [ ] Update components as needed

### PR DESCRIPTION
**Pull request by mgwalker**
- adds a `hide_if_all` display conditional
- updates section 1 to use the `hide_if_all` conditional
- closes #415 

@erinzstrenio: At the bottom of section 1a, part 3, I added a new question. Eventually this question will be hidden if the answer to the previous 19 (❗ ) is no, but for your review, here's what it looks like now. I wasn't sure what the question text should be, so I'm asking. 😄

screenshot of new question

### CODE REVIEW

**Review by tadhg-ohiggins — APPROVED** [review]
And slowly the total logical power of the conditional support in the JSON grows…

**Comment by tadhg-ohiggins** [comment]
Ready to merge after @erinzstrenio approves Q20.

**Comment by erinzstrenio** [comment]
Can we tweak it slightly to say: `Briefly describe why you made changes to your program.` 

This question should be added to Section 1, Part 4 too. 

Updated the [google doc](https://docs.google.com/document/d/1P6mFgRd8dsm1YIiHo1pDcIzWA119k5tIKNGTbbC9WVQ/edit). Also DSCP had some edits to Section 1, including removing some questions in Part 4, which I updated in the google doc. Not sure if we want to make those changes now or in one go with other edits later.

**Comment by mgwalker** [comment]
Heck, let's go ahead and get it right. 😄  Are the other changes for section 1 highlighted in the doc? If not, I can just compare what's in the app to see the changes, and I can ask if I need any clarifications?

**Comment by erinzstrenio** [comment]
@mgwalker I didn't track changes on the other edits but I can easily highlight them if that'd be helpful

**Comment by mgwalker** [comment]
No worries, I'll compare. It'll be a good excuse to spend more time getting to know the content, too.

**Comment by mgwalker** [comment]
Here are the changes I found/implemented:

- Part 1
   - question 2b only shows up if the answer to question 2a is `yes`
- Part 2
   - question 2b only shows up if the answer to question 2a is `yes`
- Part 3
   - added hint to question 6
   - inserted question 21, "Briefly describe why you made changes to your program", only shows up if any of questions 1-19 is `yes`
   - question 22 only shows up if any of questions 1-19 is `yes`
- Part 4
   - added hint to question 6
   - inserted question 21, "Briefly describe why you made changes to your program", only shows up if any of questions 1-19 is `yes`
   - question 22 only shows up if any of questions 1-19 is `yes`

**Pull request merged**
