### PR TITLE
update REDIRECT_SIGNOUT based on env

### PR DESCRIPTION
**Pull request by ailZhou**
### Description

Copying what was done on this branch: https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/11386

Updating env & logout to redirect to these pages when users signout: 
prod: https://idm.cms.gov/app/UserHome
val: https://impl.home.idm.cms.gov/app/UserHome
test: https://test.home.idm.cms.gov/app/UserHome

### Related ticket(s)

MDCT-2674

---
### How to test

N/A

### Important updates

---
### Author checklist

- [x] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by britt-mo — DISMISSED** [review]

**Review by gmrabian — DISMISSED** [review]
lgtm assuming vars are already in AWS

**Review by BearHanded — CHANGES_REQUESTED** [review]
This one is going to need a post-logout page as well 😢

**Review by keeysnc — DISMISSED** [review]
lgtm!

**Review by keeysnc — APPROVED** [review]

**Review by BearHanded — APPROVED** [review]
Looks solid, verifying in main after deploy

**Pull request merged**
